electricity_data <- read.csv2('household_power_consumption.txt',header = TRUE, sep = ";")
electricity_day1_data <- subset(electricity_data, electricity_data$Date == "1/2/2007")
electricity_day2_data <- subset(electricity_data, electricity_data$Date == "2/2/2007")
electricity_two_day_data <- rbind(electricity_day1_data,electricity_day2_data)
electricity_two_day_data$Date <- as.Date(electricity_two_day_data$Date, format = "%d/%m/%Y")
electricity_two_day_data$Time <- strptime(electricity_two_day_data$Time, format = "%H:%M:%S")
electricity_two_day_data$Time[1:1440] <- format(electricity_two_day_data$Time[1:1440], format="2007-02-01 %H:%M:%S")
electricity_two_day_data$Time[1440:2880] <- format(electricity_two_day_data$Time[1440:2880], format="2007-02-02 %H:%M:%S")
png(filename = "Plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
with(electricity_two_day_data,{
plot(Time, as.numeric(as.character(Global_active_power)), type="l",xlab = "", ylab = "Global Active Power")
plot(Time, as.numeric(as.character(Voltage)), type="l",xlab = "datetime", ylab = "Voltage")
plot(Time, as.numeric(Sub_metering_1), type = "n", xlab = "", ylab = "Energy sub metering")
lines(Time, as.numeric(as.character(Sub_metering_1)), xlab = "", ylab = "Energy sub metering")
lines(Time, as.numeric(as.character(Sub_metering_2)), xlab = "", ylab = "Energy sub metering", col = "red")
lines(Time, as.numeric(as.character(Sub_metering_3)), xlab = "", ylab = "Energy sub metering", col = "blue")
legend("topright",lty = 1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex = 0.7)
plot(Time, as.numeric(as.character(Global_reactive_power)), type="l",xlab = "datetime", ylab = "Global_reactive_power")
})
dev.off()